kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: netappsnapshot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netappsnapshot
subjects:
- kind: ServiceAccount
  name: default
  namespace: runai-lane-detection
